### ISSUE TITLE
Some images don't exist in repository

### ISSUE THREAD

**Issue by owreaser** [ExocosmoProgrammer/Exocosmo#4]
Example, sandstoneInInventory.png.

You should probably just reupload the images folder

**Comment by ExocosmoProgrammer** [comment]
I have added a branch called 'new' that I believe should have every image
in exocosmo so far. I will separate class definitions into different files.

**Comment by owreaser** [comment]
Okay, sounds good!

Just so you know, if you say put the `Player` class in the file `player.py`, you can import it from the main file using `from player import Player`, or you can do `import player` and use the class with `player.Player`.

**Comment by ExocosmoProgrammer** [comment]
Hello Owen, how's it going? Sorry if you have already received one or two
emails from me that look almost identical to this email. I have been having
difficulties with gmail, so it seems my first two attempts to send emails
like this have failed. In the case that you have read an email
hardly different than this from me, the only important part of this email
is that for me, your email shows up as ***@***.*** I want to
give you access to a video of an issue I am having on drive, but I do not
know your email. I have some questions regarding the process of
separating classes to different files. I was trying to separate class
definitions into different files, but Undefined classes or definitions
within the files with class definitions were causing NameErrors. It seemed
to me that importing definitions and classes into the files containing
class definitions would be a fix for the NameErrors, but I cannot import
anything from the main file into files imported into the main file without
causing an import error. I tried putting the room definition, which caused
a NameError, in the try part of a try except NameError loop, which did not
stop the NameError. Do you know why a try except NameError loop might fail
to stop a NameError? Do you know any workaround to the process of importing
everything used in files with class definitions into the files? Do you have
any advice on how to efficiently separate the classes to different files?
Thanks,
Gabriel

**Comment by owreaser** [comment]
Hey,This is the only email I received.My email is ***@***.***, I think github was just censoring it.If you share it to there and let me know when you do so, I'll take a look at it and try to help you fix it.Also, if you make a branch or pull request with the problem files, or share a google drive folder with them, I can take a look at it that way too.The way imports work is if you import a file, say "cat.py" from another file, say "main.py" with "import cat" or "from cat import xyz", it directly runs the file, and allows importing any named variable, class, function, etc. Because of this, it is best to *define* the classes in the file, in this case "cat.py", however in the main file (main.py), you would then set the class to something, for example "variable = cat.classname(args)" if you didnt use from to import.Along with that, if you have a function, say "isItCat()" in the main file, that is not translated into the other file, so you would have to either put that function as an argument into the cat.classname class, or you could make a separate file for the helper functions, say "helper.py", and import it into the "cat.py" file with "from helper import isItCat" or "import helper" in order to use it.A side effect of imports running the file is that if you import the main file, it is also importing the imports again, along with potentially getting stuck in the game loop.Hope this helps!Owen ReaserOn 13 Aug 2023, at 15:21, ExocosmoProgrammer ***@***.***> wrote:﻿
Hello Owen, how's it going? Sorry if you have already received one or two

emails from me that look almost identical to this email. I have been having

difficulties with gmail, so it seems my first two attempts to send emails

like this have failed. In the case that you have read an email

hardly different than this from me, the only important part of this email

is that for me, your email shows up as ***@***.*** I want to

give you access to a video of an issue I am having on drive, but I do not

know your email. I have some questions regarding the process of

separating classes to different files. I was trying to separate class

definitions into different files, but Undefined classes or definitions

within the files with class definitions were causing NameErrors. It seemed

to me that importing definitions and classes into the files containing

class definitions would be a fix for the NameErrors, but I cannot import

anything from the main file into files imported into the main file without

causing an import error. I tried putting the room definition, which caused

a NameError, in the try part of a try except NameError loop, which did not

stop the NameError. Do you know why a try except NameError loop might fail

to stop a NameError? Do you know any workaround to the process of importing

everything used in files with class definitions into the files? Do you have

any advice on how to efficiently separate the classes to different files?

Thanks,

Gabriel

**Comment by ExocosmoProgrammer** [comment]
Hello. In your last email to me, the text where you said your email showed
up as  ***@***.*** .  Are your github settings to make your email address
private?
Thanks,
Gabriel

**Comment by owreaser** [comment]
Hey,It seems that these messages are going through github, and github must censor it on its end.Hopefully this goes through, my email is:owreaser at gmail dot comThanks!Owen ReaserOn 14 Aug 2023, at 20:02, ExocosmoProgrammer ***@***.***> wrote:﻿
Hello. In your last email to me, the text where you said your email showed

up as  ***@***.*** .  Are your github settings to make your email address

private?

Thanks,

Gabriel



On Sun, Aug 13, 2023 at 12:41 PM Owen Reaser ***@***.***>

wrote:



> Hey,This is the only email I received.My email is ***@***.***, I think

> github was just censoring it.If you share it to there and let me know when

> you do so, I'll take a look at it and try to help you fix it.Also, if you

> make a branch or pull request with the problem files, or share a google

> drive folder with them, I can take a look at it that way too.The way

> imports work is if you import a file, say "cat.py" from another file, say

> "main.py" with "import cat" or "from cat import xyz", it directly runs the

> file, and allows importing any named variable, class, function, etc.

> Because of this, it is best to *define* the classes in the file, in this

> case "cat.py", however in the main file (main.py), you would then set the

> class to something, for example "variable = cat.classname(args)" if you

> didnt use from to import.Along with that, if you have a function, say

> "isItCat()" in the main file, that is not translated into the other file,

> so you would have to either put that function as an argument into the

> cat.classname class, or you could make a separate file for the helper

> functions, say "helper.py", and import it into the "cat.py" file with "from

> helper import isItCat" or "import helper" in order to use it.A side effect

> of imports running the file is that if you import the main file, it is also

> importing the imports again, along with potentially getting stuck in the

> game loop.Hope this helps!Owen ReaserOn 13 Aug 2023, at 15:21,

> ExocosmoProgrammer ***@***.***> wrote:﻿

> Hello Owen, how's it going? Sorry if you have already received one or two

>

> emails from me that look almost identical to this email. I have been

> having

>

> difficulties with gmail, so it seems my first two attempts to send emails

>

> like this have failed. In the case that you have read an email

>

> hardly different than this from me, the only important part of this email

>

> is that for me, your email shows up as ***@***.*** I want to

>

> give you access to a video of an issue I am having on drive, but I do not

>

> know your email. I have some questions regarding the process of

>

> separating classes to different files. I was trying to separate class

>

> definitions into different files, but Undefined classes or definitions

>

> within the files with class definitions were causing NameErrors. It seemed

>

> to me that importing definitions and classes into the files containing

>

> class definitions would be a fix for the NameErrors, but I cannot import

>

> anything from the main file into files imported into the main file without

>

> causing an import error. I tried putting the room definition, which caused

>

> a NameError, in the try part of a try except NameError loop, which did not

>

> stop the NameError. Do you know why a try except NameError loop might fail

>

> to stop a NameError? Do you know any workaround to the process of

> importing

>

> everything used in files with class definitions into the files? Do you

> have

>

> any advice on how to efficiently separate the classes to different files?

>

> Thanks,

>

> Gabriel

>

>

>
